config/routes.rb
Rails.application.routes.draw do

  resources :styles

  resources :memberships

  resources :beer_clubs

  resources :beers
  resources :breweries
  resources :users
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :places, only: [:index, :show]

  resource :session, only: [:new, :create, :delete]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'beerlist', to: 'beers#list'
  get 'ngbeerlist', to: 'beers#nglist'
  get 'brewerylist', to: 'breweries#list'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'

  post 'places', to: 'places#search'

  delete 'signout', to: 'sessions#destroy'

  put 'confirm_membership', to: 'memberships#confirm'

  root 'breweries#index'

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :users do
    post 'toggle_suspend', on: :member
  end

end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
    has_many :memberships, dependent: :destroy
    has_many :users, through: :memberships

    def to_s
        "#{name}, #{city}"
    end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_that_admin, only: [:destroy]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
      if current_user && @beer_club.users.include?(current_user)
        @membership = @beer_club.memberships.find_by_user_id(current_user.id)
      else
        @membership = Membership.new
      end
      @membership.beer_club = @beer_club
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        ms = Membership.create(user_id: current_user.id,
                               beer_club_id: @beer_club.id,
                               confirmed: true)
        current_user.memberships << ms
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city)
    end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-5">
    <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control' %>
    <%= f.label :founded %>
    <%= f.number_field :founded, class:'form-control' %>
    <%= f.label :city %>
    <%= f.text_field :city, class:'form-control' %>
    </div>
    <%= f.submit 'Create beer club', class:'btn btn-primary' %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<h1>Listing Beer Clubs</h1>

<div class="col-md-10">
<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= link_to beer_club.name, beer_club %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to('New Beer club', new_beer_club_path, class: 'btn btn-primary') if current_user %>
</div>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form' %>

app/views/beer_clubs/show.html.erb
<h2><%= @beer_club.name %>, <%= @beer_club.city %></h2>

<p>Founded in <%= @beer_club.founded %></p>

<p><strong>Members</strong></p>

<ul>
  <% @beer_club.memberships.confirmed.each do |membership| %>
    <li><%= link_to membership.user.username, membership.user %></li>
  <% end %>
</ul>
<% if @beer_club.memberships.confirmed.empty? %><p>No members yet!</p><% end %>

<% if current_user && @beer_club.memberships.confirmed.exists?(user_id:current_user.id) %>
  <p><strong>Outstanding applications</strong></p>

  <ul>
    <% @beer_club.memberships.applications.each do |application| %>
      <li>
        <%= link_to application.user.username, application.user %>
        <%= link_to 'confirm',
          confirm_membership_path(user_id: application.user.id,
                                  beer_club_id: @beer_club.id),
          method: :put, class: "btn btn-primary btn-xs" %>
    </li>
  <% end %>
  </ul>
  <% if @beer_club.memberships.applications.empty? %>
    <p>No applications outstanding!</p>
  <% end %>
<% end %>

<% if current_user && @beer_club.memberships.applications.exists?(user_id:current_user.id) %>
  <strong>Your application to join the club is awaiting approval!</strong>
<% elsif current_user && !@membership.beer_club.users.include?(current_user) %>
  <div class="form-group">
    <%= form_for(@membership) do |f| %>
      <%= f.hidden_field :beer_club_id %>
      <%= f.submit value:"join the club", class:'btn btn-primary' %>
    <% end %>
  </div>
<% elsif current_user && @beer_club.memberships.confirmed.count > 1 %>
  <div class="form-group">
    <%= form_for(@membership, method: "delete") do |f| %>
      <%= f.hidden_field :beer_club_id %>
      <%= f.submit value: "end your membership", class:'btn btn-danger' %>
    <% end %>
  </div>
<% end %>
<p></p>

<% if current_user %>
  <%= link_to 'Edit club', edit_beer_club_path(@beer_club), class: "btn btn-primary" %>
  <%= link_to 'Destroy club', beer_club_path(@beer_club), method: :delete,
    data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
<% end %>