config/routes.rb
Rails.application.routes.draw do

  resources :styles

  resources :memberships

  resources :beer_clubs

  resources :beers
  resources :breweries
  resources :users
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :places, only: [:index, :show]

  resource :session, only: [:new, :create, :delete]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'beerlist', to: 'beers#list'
  get 'ngbeerlist', to: 'beers#nglist'
  get 'brewerylist', to: 'breweries#list'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'

  post 'places', to: 'places#search'

  delete 'signout', to: 'sessions#destroy'

  put 'confirm_membership', to: 'memberships#confirm'

  root 'breweries#index'

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :users do
    post 'toggle_suspend', on: :member
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include AverageRating

  has_secure_password

  validates :username, uniqueness: true,
    length: { in: 3..20 }
  validates :password, length: { minimum: 4 },
    format: { with: /([A-Z]\D*\d|\d\D*[A-Z])/,
              message: "must contain at least one capital letter and one number" }

    has_many :ratings, dependent: :destroy
    has_many :beers, through: :ratings
    has_many :memberships, dependent: :destroy
    has_many :beer_clubs, through: :memberships

    def self.github(info)
      user = User.find_by username:info.nickname
      if user.nil?
      password = SecureRandom.base64
      user = User.create!(username: info.nickname,
                          password: password,
                          password_confirmation: password)
      end
      user
    end

    def self.top_raters(n)
      User.all.sort_by{ |u| -(u.ratings.count||0) }.take(n)
    end

    def favorite_beer
      return nil if ratings.empty?
      ratings.order(score: :desc).limit(1).first.beer
    end

    def favorite_style
      favorite :style
    end

    def favorite_brewery
      favorite :brewery
    end

    def favorite(category)
      return nil if ratings.empty?
      rated(category).max_by do |item|
        ratings_by_item = ratings_by(category, item)
        ratings_by_item.map(&:score).sum / ratings_by_item.count
      end
    end

    def rated(category)
      ratings.map { |r| r.beer.send(category) }.uniq
    end

    def ratings_by(category, item)
      ratings.select { |r| r.beer.send(category).eql? item }
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:beers, :ratings).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def toggle_suspend
    user = User.find(params[:id])
    user.update_attribute :suspended, (not user.suspended)
    new_status = user.suspended? ? "frozen" : "active"
    redirect_to :back, notice:"user activity status changed to #{new_status}"
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and
          @user.update(user_params) and 
          @user == current_user
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy if @user == current_user
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-5">
    <div class="form-group">
  <% if @user.new_record? %>
        <%= f.label :username %>
        <%= f.text_field :username, class:'form-control' %>
  <% end %>
    <%= f.label :password %>
    <%= f.password_field :password, class:'form-control' %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class:'form-control' %>
    </div>
    <%= f.submit 'Create User', class:'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.username %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<div class="col-md-10">

  <table class="table table-condensed table-hover">
    <thead>
      <tr>
        <th>Username</th>
        <th></th>
        <th> rated beers </th>
        <th> total ratings </th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.username, user %></td>
          <td>
            <% if user && user.admin? %>
              <div class="label label-info">admin</div>
            <% end %>
            <% if current_user && current_user.admin? && user.suspended? %>
              <div class="label label-warning">account frozen</div>
            <% end %>
          </td>
          <td><%= user.beers.size %></td>
          <td><%= user.ratings.size %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New User', new_user_path, class: 'btn btn-primary' %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="col-md-12">
<div class="col-md-5"><h2><%= @user.username %></h2></div>
<div class="col-md-5 top-margin">
  <% if @user && @user.admin? %><div class="label label-info">admin</div><% end %>
  <% if current_user && current_user.admin? && @user.suspended? %>
    <div class="label label-warning">account frozen</div>
  <% end %>
</div>
</div>

<% if !@user.ratings.empty? %>
  <p>Has made <%= pluralize @user.ratings.count, 'rating', 'ratings' %>, average <%= round @user.average_rating %></p>

  <p>Favorite beer style is <strong><%= @user.favorite_style %></strong> 
  and brewery <strong><%= @user.favorite_brewery.name %></strong></p>
<% end %>

<% if !@user.memberships.confirmed.empty? %>
  <strong>Member of</strong>
  <ul>
    <% @user.memberships.confirmed.each do |membership| %>
      <li><%= link_to membership.beer_club.name, membership.beer_club %></li>
    <% end %>
  </ul>
<% end %>

<% if !@user.memberships.applications.empty? %>
  <strong>Applied membership of</strong>
  <ul>
    <% @user.memberships.applications.each do |application| %>
      <li><%= link_to application.beer_club.name, application.beer_club %></li>
    <% end %>
  </ul>
<% end %>

<p><strong>Ratings:</strong></p>
<% if @user.ratings.empty? %><p>No ratings yet!</p><% end %>
<ul>
  <% @user.ratings.each do |rating| %>
    <li><%= rating %>
    <% if @user == current_user %>
      <%= link_to 'delete', rating, method: :delete, data: { confirm: 'are you sure?' } %>
    <% end %></li>
  <% end %>
</ul>



<% if @user == current_user %>
  <%= link_to 'Change password', edit_user_path(@user), class: 'btn btn-primary' %>
  <%= link_to 'Destroy account', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %> 
<% end %>
<% if current_user && current_user.admin? %>
  <% link_text = @user.suspended ? 'Reactivate account' : 'Freeze account' %>
  <%= link_to link_text, toggle_suspend_user_path(@user), method: :post, class: 'btn btn-danger' %>
<% end %>